Attr tracking
NOAA-OWP/gval pull request #142
Opened 2023-07-24 19:00 UTC by fernando-aristizabal

Closes #132 
- Implements within file attribute tracking.
- Tags raster attributes from candidate and benchmark to an attributes df along with agreement map.
- Uses attributes df schema
- Implements tests.
- Creates attribute tracking accessor method.
- Implements attribute tracking within continuous and categorical compare accessor methods.

2023-07-24 19:08 UTC, fernando-aristizabal commented
Made some changes as apparently it wasn't passing linting. Great use of automation!

2023-07-26 16:39 UTC, GregoryPetrochenkov-NOAA requested changes

2023-07-26 19:43 UTC, fernando-aristizabal commented on src/gval/accessors/gval_xarray.py
> +        Union[
Good catch.

2023-07-26 19:44 UTC, fernando-aristizabal commented on src/gval/accessors/gval_xarray.py
> +        Union[
Changed.

2023-07-26 19:54 UTC, fernando-aristizabal commented
Ready to review @GregoryPetrochenkov-NOAA pending successful CI builds and tests.

2023-07-26 20:56 UTC, GregoryPetrochenkov-NOAA approved these changes

2023-07-26 20:58 UTC, merged